name: health_app_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  image_picker: ^1.0.7 # Updated version
  firebase_storage: ^12.4.1 # Added
  uuid: ^4.3.3 # Added
  intl: ^0.20.1
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  timezone: ^0.10.0
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Daily Bites Logo.png"
  adaptive_icon_foreground: "assets/Daily Bites Outline White.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_monochrome: "assets/Daily Bites Outline Monochrome.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Daily Bites Logo.png
    - .env  # Uncomment this line only if you add a .env file to your project root